# This file was generated by GoReleaser. DO NOT EDIT.
class Gravitywell < Formula
  desc ""
  homepage ""
  url "https://github.com/AlexsJones/gravitywell/releases/download/v0.6.1/gravitywell_0.6.1_darwin_amd64.tar.gz"
  version "0.6.1"
  sha256 "8fe0e5786a6e70c81619cb8138133d643a0babb8052bf12d335164f541d9d40d"

  def install
    bin.install "gravitywell"
  end
end
