# This file was generated by GoReleaser. DO NOT EDIT.
class Gravitywell < Formula
  desc ""
  homepage ""
  url "https://github.com/AlexsJones/gravitywell/releases/download/v0.7.1/gravitywell_0.7.1_darwin_amd64.tar.gz"
  version "0.7.1"
  sha256 "b640cab12c3a6b050e622db71a00ebda969b2bf6d0da9201aa339adc503fb37c"

  def install
    bin.install "gravitywell"
  end
end
