# This file was generated by GoReleaser. DO NOT EDIT.
class Gravitywell < Formula
  desc ""
  homepage ""
  url "https://github.com/AlexsJones/gravitywell/releases/download/v0.6.2/gravitywell_0.6.2_darwin_amd64.tar.gz"
  version "0.6.2"
  sha256 "68ffbb1aaef0a6c73c0af3eda66b67df53966692fc83ea07a31e628574ed6c17"

  def install
    bin.install "gravitywell"
  end
end
