# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewGravitywell < Formula
  desc ""
  homepage ""
  url "https://github.com/AlexsJones/gravitywell/releases/download/v0.6.0/gravitywell_0.6.0_darwin_amd64.tar.gz"
  version "0.6.0"
  sha256 "75cb78bb598270fc2881a1e7300f991f0855c5bef78ca8d625055df0709ab2b4"

  def install
    bin.install "gravitywell"
  end
end
